/**
 * You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.


*/

#include<bits/stdc++.h>
using namespace std;

//write your function here
class Solution {
public:
    // time complexity = O(len(t))
    // space = O(1)
    char findTheDifference(string s, string t) {
        // we will do xor operation
        char ans='0'; // you can initialize with any char
        for(auto c: s)
            ans = ans ^ c;
        
        for(auto c: t)
            ans = ans ^ c;
        
        ans = ans ^ '0';
        return ans;
    }
};

int main(){
    string s = "abc";
    string t = "abcd";
    Solution ob;
    cout<<ob.findTheDifference(s, t)<<endl;
    return 0;
}